### PR TITLE
This disables authentication in mysql

### PR DESCRIPTION
**Pull request by pawel-yesware**
- Only root user is created without password
- No custom dbs are created

@justin-yesware @mkostick

### CODE REVIEW

**Comment by justinmills** [comment]
I think I like #1 a bit better. It also seems to have more of a chance to get merged back into mainline. That said, I'm fine with either, as this is really just for local development.

**Comment by pawel-yesware** [comment]
They said that they won't merge plugins using env variables for customization of docker images

**Comment by pawel-yesware** [comment]
here is my PR for postgresql plugin https://github.com/dokku/dokku-postgres/pull/50

**Comment by justinmills** [comment]
Yeah, I hadn't read all of the referenced post. I'm not sure I follow their reasoning, as it sounds like the beginning of a slipper slope where you support all DDL commands via dokku commands. Also, things like `postgres:create-user` would wind up getting into permission issues (what permissions to grant, etc). Seems like you'd like the ability to have this provision a database for you and by default generate a username/password for you, but if you have a set username/password you'd like to use, pass that in. From there you can use that user to perform any other DDL you like. Maybe that's just my take though. I'm not 100% up to speed on the underlying purpose of dokku.

That said, I think I still like the idea of #1, as it's more in line with our fork of the pg dokku repo.

**Pull request merged**
